services:
  - type: web
    name: url-shortener-springboot
    runtime: java
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/url-shortner-sb-0.0.1-SNAPSHOT.jar"
    plan: free